---
abstract: 'Write Perl subroutines and classes in C++.'
author:
  - 'David Oswald <davido@cpan.org>'
build_requires:
  Config: 0
  English: 0
  Test::More: 0.98
configure_requires:
  Config: 0
  ExtUtils::MakeMaker: 6.56
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Inline-CPP
no_index:
  directory:
    - t
    - inc
provides:
  Inline::CPP:
    file: CPP.pm
    version: 0.39
  Inline::CPP::Config:
    file: lib/Inline/CPP/Config.pm
    version: 0.39
  Inline::CPP::grammar:
    file: grammar/grammar.pm
    version: 0.39
requires:
  Carp: 0
  Inline: 0.50
  Inline::C: 0.50
  Parse::RecDescent: 0
  perl: 5.006001
version: 0.40
