---
abstract: 'Write Perl subroutines and classes in C++.'
author:
  - 'David Oswald <davido@cpan.org>'
build_requires:
  Config: '0'
  English: '0'
  Test::More: '0.98'
configure_requires:
  Config: '0'
  ExtUtils::CppGuess: '0.07'
  ExtUtils::MakeMaker: '6.56'
  FindBin: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Inline-CPP
no_index:
  directory:
    - t
    - inc
    - inc
provides:
  Inline::CPP:
    file: lib/Inline/CPP.pm
    version: '0.56'
  Inline::CPP::Config:
    file: lib/Inline/CPP/Config.pm
    version: '0.56'
  Inline::CPP::Grammar:
    file: lib/Inline/CPP/Grammar.pm
    version: '0.56'
requires:
  Carp: '0'
  Inline: '0.67'
  Inline::C: '0.62'
  Parse::RecDescent: '0'
  perl: '5.006001'
resources:
  homepage: http://github.com/daoswald/Inline-CPP
  license: http://dev.perl.org/licenses/artistic.html
  repository: http://github.com/daoswald/Inline-CPP.git
version: '0.56'
